# Generated by Django 5.0.6 on 2024-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_remove_scheduling_notes_scheduling_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='day',
            field=models.DateField(verbose_name='Day required'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='item',
            field=models.CharField(choices=[('Laptop', 'is a laptop'), ('Desktop', 'like a non portable laptop'), ('Mobile', 'like a very portable laptop'), ('Camera', 'for taking photos')], default='Camera', max_length=32, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='person',
            field=models.CharField(default='USER', max_length=32, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='returntime',
            field=models.TimeField(verbose_name='Return time'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='timebooked',
            field=models.TimeField(verbose_name='Time needed'),
        ),
    ]
